### ISSUE TITLE
TaurusLabel Widget stop updating after message Qt: Object::disconnect: Unexpected null parameter in taurusrootlogger

### ISSUE THREAD

**Issue by tcsgmrt** [taurus-org/taurus#731] opened 2018-03-26 11:36 UTC
Hello All,

We have used taurus label to read value of  some attributes like IST time, status etc. we have observed that due to some server issue(push heart beat event) taurus label stops updating attribute value.

Below are logs at terminal while running application:
```
TimerLoop 1 WARNING 2018-03-26 16:11:35,923 TaurusPollingTimer[1000].Timer on _pollAttributes: loop function took more than loop interval (1.0s)
 
MainThread WARNING 2018-03-26 16:11:58,635 TaurusRootLogger: Qt: Object::disconnect: Unexpected null parameter
```

During this scenario if we launch another taurus gui instance then older gui instance start updating the taurus label value automatically. we are not able to debug this behavior and it's cause.

Any help would be appreciated.

Thanks,
TCS, GMRT

**Comment by cpascual** [comment] 2018-03-26 12:14
Hi, 
have you checked if the server is actually sending events after you see the freeze?

You could check by adding a PyTango listener...

```python
import tango
t = tango.DeviceProxy("<YOUR/DEVICE/MODEL>")
id = t.subscribe_event("YOURATTRIBUTE", tango.EventType.CHANGE_EVENT, tango.utils.EventCallBack())
```

... and (in a different ipython console) a Taurus listener:

```python
import taurus

def cb(*args):
    print args

a = taurus.Attribute('<YOUR_ATTR_MODEL>')
a.addListener(cb)
```

You should see traces appearing in both consoles. Otherwise, I think you need to check your server (which is out of the scope of Taurus)

**Comment by cpascual** [comment] 2018-03-26 12:16
Also, in case you are doing experiencing this with Taurus 3.x please try to reproduce it with Taurus 4

**Comment by tcsgmrt** [comment] 2018-03-26 12:29
Thanks for prompt reply. I will check with suggestion provided by you and get back to you.

Thanks,
TCS, GMRT

**Comment by tcsgmrt** [comment] 2018-03-26 13:05
Hi,

I have tried your suggestion for above scenario. After seeing a taurus label freeze, I have subscribe that attribute change event from IPYTHON terminal and I have received change event from server and also at same time taurus label value for that attribute started updating on GUI application. We have observed this behavior for most of the attribute.  

Are there any server event is stopping event mechanism for attributes? 

Thanks,
TCS, GMRT

**Comment by cpascual** [comment] 2018-03-26 13:24
> After seeing a taurus label freeze, I have subscribe that attribute change event from IPYTHON terminal and I have received change event from server and also at same time taurus label value for that attribute started updating on GUI application.

This is consistent with what you originally reported ("  if we launch another taurus gui instance then older gui instance start updating the taurus label value automatically")

But this is not what I had in mind in my suggestion. What I intended  is that you did the subscription **before** . i.e.  **first** subscribe on the ipyhton console and **then** launch your GUI. and in that case:

a) does the GUI stop updating values?
b) if so, does the ipython console still print traces of new events or it also stopped receiving events?

**Comment by tcsgmrt** [comment] 2018-03-28 10:21
Hi,

I have tried your suggestion by start listening **IST** attribute change event  at IPython terminal. 
We have observed that when GUI Tauruslabel stop updating the attribute value same time the attribute at IPython terminal also stop updating.

At terminal we received following message.
**2018-03-28 14:57:59.556009 MNC/LMC/GSB IST CHANGE [ATTR_VALID] 14:57:59
2018-03-28 14:58:00.556907 MNC/LMC/GSB IST CHANGE [ATTR_VALID] 14:58:00
Wed Mar 28 14:59:22 2018: Tango::ZmqEventConsumer::push_heartbeat_event() timeout on channel monitor of tango://lmccorr:10000/dserver/lmcds/gsb**

Does Tango unsubscripted attribute change event after receiving  Tango::ZmqEventConsumer::push_heartbeat_event() ?    

Thanks,
TCS,GMRT

**Comment by cpascual** [comment] 2018-04-03 07:19
> We have observed that when GUI Tauruslabel stop updating the attribute value same time the attribute at IPython terminal also stop updating.

This indicates that the problem is likely not in Taurus (probably it is in the Device Server or in the network).

> ```Wed Mar 28 14:59:22 2018: Tango::ZmqEventConsumer::push_heartbeat_event() timeout on channel monitor of tango://lmccorr:10000/dserver/lmcds/gsb```

Note that this message already indicates some communication issue. Maybe there is a firewall preventing certain events to reach the client?

> Does Tango unsubscripted attribute change event after receiving Tango::ZmqEventConsumer::push_heartbeat_event() ?

I don't think so. It looks more like the heart beat event did not reach the client (and then maybe the subscription is deactivated... 

My suggestion is that you first ensure that nothing is blocked in your network, then that your DS is properly implemented (maybe try if you can reproduce with another, standard DS?) and finally to try to reproduce the behaviour with a dummy PyTango-only client.

In any case, I think that this is out of the scope of Taurus., so I am closing the issue. Please do not hessitate to reopen if your debugging leads back to Taurus at some point.

**Closed by cpascual** 2018-04-03 07:19 UTC
Labels: question
