### ISSUE TITLE
Unidentifiable C++ exception

### ISSUE THREAD

**Issue by Aratar93** [taurus-org/taurus#442] opened 2017-04-16 17:36 UTC
Hi all,

I have command Write, which take one character from input and send it to Serial Port.
When I want to execute this command from GUI created by Taurus this is what I get:

![pct](https://cloud.githubusercontent.com/assets/27634724/25072951/786ff0cc-22db-11e7-90fb-1f12bdb140d1.png)

From AtkPanel I am able to run this command without problem. 
Do you have any idea what's the problem?

**Comment by cpascual** [comment] 2017-04-18 09:44
Hi @Aratar93 , in order to  simplify the debugging, can you please try to run the command from an ipython console using a `PyTango.DeviceProxy` ?

If that works, do the same using use a `Taurus.Device`

Then, if all works, then try to run 
```python 
from taurus.qt.qtgui.button.taurusbutton import commandButtonMain
commandButtonMain()
```
...and send us all the output from your tests so that we can try to help.

**Comment by cpascual** [comment] 2017-04-19 07:45
I just found this internal report by @sergirubio ... I wonder if it is related:

```
BL29/VC/VGCT-04/SendCommand('PRO1') works perfect from PyTango, but
returned the following exception from a TaurusDevicePanel:

Traceback (most recent call last):

File "/homelocal/sicilia/lib/python/site-packages/vacca/lib/taurus/qt/qtgui/dialog/taurusmessagebox.py",
line 221, in wrapped
return fn(*args, **kwargs)

File "/homelocal/sicilia/lib/python/site-packages/vacca/lib/taurus/qt/qtgui/button/taurusbutton.py",
line 298, in onClicked
return self._onClicked()

File "/homelocal/sicilia/lib/python/site-packages/vacca/lib/taurus/qt/qtgui/button/taurusbutton.py",
line 329, in _onClicked
result = modelobj.command_inout(self._command,
self._castParameters(self._parameters, self._command, modelobj))

File "/homelocal/sicilia/lib/python/site-packages/PyTango/connection.py",
line 93, in _Connection_command_inout
r = Connection.command_inout_raw(self, name, *args, **kwds)

File "/homelocal/sicilia/lib/python/site-packages/PyTango/connection.py",
line 117, in _Connection_command_inout_raw
param = __get_command_inout_param(self, cmd_name, cmd_param)

File "/homelocal/sicilia/lib/python/site-packages/PyTango/connection.py",
line 61, in __get_command_inout_param
param.insert(info.in_type, cmd_param)
TypeError: No registered converter was able to extract a C++ pointer
to type char from this Python object of type list
```

**Comment by Aratar93** [comment] 2017-04-19 12:16
Hm, one stupid question. If function _Write_ expect a char as argin, do I need ValueSpinBox in which I type that char, or it will open some new window for entering char (like in AtkPanel)? 
If I need it, how to connect it with command button Write? (Also, If you know some good starter tutorial for qt designer, please recommend me :) )

Anyway, I've got next:
1. _PyTango.DeviceProxy("test/serial/1").Write("q")_ works fine.
2.  For the second one, I am not sure should I run it from ipython also, or not, so I will copy both answers.
From ipython
_In [14]: from taurus.qt.qtgui.button.taurusbutton import commandButtonMain
MainThread     INFO     2017-04-19 14:10:44,695 TaurusRootLogger: Using "PyQt4" for Qt

In [15]: commandButtonMain
Out[15]: <function taurus.qt.qtgui.button.taurusbutton.commandButtonMain>_

From terminal:
_from taurus.qt.qtgui.button.taurusbutton import commandButtonMain
from: can't read /var/mail/taurus.qt.qtgui.button.taurusbutton_
3. Also, I have one more question.
For generating python code I have used 
taurusuic4 -x -o name.py name.ui command, and this is what I got
taurusuic4 is deprecated since SEP11 (http://sf.net/p/sardana/wiki/SEP11)
Consider using the taurus.qt.qtgui.util.UILoadable decorator instead
Can this be cause of the error?

Many thank for your help

**Comment by cpascual** [comment] 2017-04-19 14:44
>  If function Write expects a char as argument, do I need ValueSpinBox in which I should type that char,

Yes, if you want the user to change the parameters of the command, you should provide mechanism yourself to do that. Since you want a string (python does not have "char"), you could use a `QLineEdit`, or using a dialog created with `QInputDialog.getText`.

Note:
Taurus already provides  `taurus.qt.qtgui.panel.TaurusCommandsForm`, which is a widget that uses `TaurusCommandButton` and `QComboBox` to execute commands of a Tango device. You can see it in the "commands" tab if you run `taurusdevicepanel your/dev/name` 

> In [21]: PyTango.DeviceProxy("test/serial/1").Write("q") works fine.
> In [22]: taurus.Device("test/serial/1").Write("q") also works.

hmmm... that seems to indicate that the problem is either a bug in TaurusCommandButton or a problem in how you set the parameter for the command...

Please try the following code:

```python
import sys
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.button import TaurusCommandButton

model = 'sys/tg_test/1'
command = 'DevString'

app = TaurusApplication()
w = TaurusCommandButton(parent=None, designMode=False, command=command,
                        parameters=['q'])
w.setModel(model)

def f(*a):
    print "Clicked. Result=", a

w.commandExecuted.connect(f)
w.show()
sys.exit(app.exec_())
```

This should give you a button, and when you click it you should see `Clicked. Result= ('q',)` printed on the console.

Now, if that works, just change the model and the command to:

```python
model = 'test/serial/1'
command = 'Write'
```

... and it should also work

If it does, then the problem may be in how you set the parameter of the TaurusCommandButton (note that it expects a list). 
If not, then please paste a simplified version of your program (the minimum possible code that allows to reproduce the issue) and we can try to debug it.

> Also, If you know some good starter tutorial for qt designer, please recommend me 

I learned with a book [Rapid GUI programming in python and Qt](https://www.qtrac.eu/pyqtbook.html) (great, but it is currently a bit outdated).
Maybe you could check: http://doc.qt.io/qt-4.8/designer-manual.html (and references therein)
For an intro to PyQt (without designer), see:
http://zetcode.com/gui/pyqt4/

> Also, I have one more question. For generating python code I have used taurusuic4 -x -o name.py name.ui command, and this is what I got: (...) deprecated (...)

As the message says, taurusuic4 is deprecated. The recommended way for generating GUIs is to *dynamically* load the .ui file everytime one launches the script (without previously compiling it with taurusuic4 or pyuic4). For a more detailed explanation, and some examples, see the [SEP11](http://www.sardana-controls.org/sep?SEP11.md)
https://github.com/sardana-org/sardana/blob/develop/doc/source/sep/SEP11.md

Note: an alternative pure-Qt way of dynamically loading the .ui file at run time can be seen in [this example](https://github.com/cpascual/pythoncourse-intermediate/blob/master/exercises/cheat/qtexercise2_uic.py)

**Comment by cpascual** [comment] 2017-04-27 05:59
Hi @Aratar93 , any news?
Is your issue gone?

**Comment by Aratar93** [comment] 2017-04-27 06:38
Hi cpascual,

Sorry for not replying so long, but I've been really busy by doing some other things in the meantime. 
However, I was able to read materials you recomended me, because I think it's the best for me to start from basics. I'm planning to deal with my problem these days, and I'll let you know how I'm doing. 
Once again thank you for your help.

Cheers,
Aratar

**Comment by Aratar93** [comment] 2017-04-30 14:29
> or a problem in how you set the parameter for the command

You were right, it was problem in parameters, However, by using your code, I haven't got anything in my terminal, but I was able to solve it like below (thanks to tutorials you recomended me):
`
QtCore.QObject.connect(self.WriteButton, QtCore.SIGNAL('clicked()'), self.clicked_Write)
 def clicked_Write(self):
        self.writeValue = self.LedWValue.text()
        self.WriteButton.setParameters(self.writeValue)
        self.WriteButton.setCommand('LED_Write')
`
I have one question though. I have command which returns string. I want to display that argument in LineEdit. But, I am not able to catch argout.
I have tried these approaches
'self.ReadButton.setCommand('LED_Read')
print(x)'
'self.ReadButton.setCommand('LED_Read')
x = self.ReadButton.getParameters()'
but all I was getting was None value.
P.S. This commands works when it is executed from AtkPanel.

**Comment by cpascual** [comment] 2017-05-02 13:50
> However, by using your code, I haven't got anything in my terminal

Please check it again (make sure that you do not change anything). I just tried and it works for me (I just copy-pasted it to be sure).

> but I was able to solve it like below (...)

Your solution has a few issues:

- it is using old-style signals. Unless you are using an old version of Taurus and of PyQt, I recommend to use [new style signals](http://pyqt.sourceforge.net/Docs/PyQt4/new_style_signals_slots.html) (as in my example). 
- It connects the `clicked` signal, not the `commandExecuted` one. The `commandExecuted` signal passes the return value of the command as its argument, which you can then print in your slot. 

> I have one more question though.
> I have command which returns string, and want to print that argout. But, I am not able to do that. (...)

See my code: I am printing the return value of the `DevString` command, obtained from the  `commandExecuted` signal argument

**Comment by Aratar93** [comment] 2017-05-04 09:32
Hi,

I have tried again and it worked. Don't know what I was doing wrong the first time.
I have few more questions though.

First one is happening quite often. PyQt just freeze, and I can't do anything. Sometimes whole Ubuntu get frozened. In the terminal from which is Taurus is started this is what I get (and I think this is causing problem):
`TimerLoop 1    WARNING  2017-05-04 11:12:40,643 TaurusPollingTimer[3000].Timer on _pollAttributes: loop function took more than loop interval (3.0s)`
And I have lots of this repeating, even though my GUI isn't started.

The second two questions are about visual style. For TaurusWheelEdit, I'm putting that it have 0 decimal digits, but that's not doing anything, two decimal digits are always coming back. Also, title for the TaurusCommandButton is not what I'm setting in property table.

And finally, one of TaurusWheelEdit's model is set as 'modbus/PLC/1/Voltage'. But when I change this value from GUI, nothing is happening,  attribute is still remaining the same. Should I do something more to link TaurusWheelEdit and attribute in Tango?

Many thanks,
Aratar

**Comment by Aratar93** [comment] 2017-05-04 09:47
And one more
`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/input/taurusspinbox.py", line 96, in stepEnabled
    if self.validate(str(curr_val + ss), 0)[0] == Qt.QValidator.Acceptable:
  File "/usr/local/lib/python2.7/dist-packages/taurus/external/pint/pint_local/quantity.py", line 566, in __add__
    return self._add_sub(other, operator.add)
  File "/usr/local/lib/python2.7/dist-packages/taurus/external/pint/pint_local/quantity.py", line 503, in _add_sub
    magnitude = op(self._magnitude, other._magnitude)
TypeError: unsupported operand type(s) for +: 'QString' and 'float'`

What does this mean, I'm getting this when I want to link attribute and QSpinBox?

**Comment by cpascual** [comment] 2017-05-17 07:14
Hi @Aratar93 :

> I have tried again and it worked. Don't know what I was doing wrong the first time.

Good to hear. I will close the issue then.

> I have few more questions though.

In the future, please open separate issues for independent questions. That way we keep this focused and useful for future reference.

> PyQt just freeze, and I can't do anything. Sometimes whole Ubuntu get frozened. In the terminal from which is Taurus is started this is what I get (and I think this is causing problem):
TimerLoop 1 WARNING 2017-05-04 11:12:40,643 TaurusPollingTimer[3000].Timer on _pollAttributes: loop function took more than loop interval (3.0s)
And I have lots of this repeating, even though my GUI isn't started.

Not necessarily a cause, but just another symptom. The message you mention just warns that the machine could not complete all the polling requests within 3s. This may be due to some attribute that takes too long to read, or because some other process is eating too much resouces... My advice for debugging is to try to radically simplify your GUI (comment out most of it) and enable parts one at a time to find what is causing the problem. Running it on a clean environment may also help.
 
> For TaurusWheelEdit, I'm putting that it have 0 decimal digits, but that's not doing anything, two decimal digits are always coming back. 

Please try again with the latest code in develop (recent changes from #444 may have changed this), and if this still happens, please open an issue detailing step-by-step  how to reproduce your problem

> Also, title for the TaurusCommandButton is not what I'm setting in property table.

Please open an issue detailing exactly what you do and what you expect.

> And finally, how can I update attribute's value by reading value from ValueSpinBox or WheelEdit?

Not sure of what you mean. Note that both ValueSpinBox and WheelEdit are "write widgets". This means that they deal exclusively with the attribute's `.wvalue` (as opposed to a TaurusLabel, which by default shows the `.rvalue`). Also, note that the both are already connected and receiving updates from the attribute but, to avoid messing with the user's edition, if the updated wvalue differs from the one shown by the widgets, they do *not* change the displayed one. Instead they show the "conflict" by showing that there are "pending operations" ([More explanations here](http://www.taurus-scada.org/en/latest/users/ui/forms.html?highlight=pending%20operations#writing-to-attributes)).

Also note that if you want a widget that simultaneously shows the `rvalue` and the `wvalue` you can get it with [TaurusLabelEditRW](http://www.taurus-scada.org/en/latest/devel/api/taurus/qt/qtgui/compact/_TaurusLabelEditRW.html) or create your own combination of read and write with [TaurusReadWriteSwitcher](http://www.taurus-scada.org/en/latest/devel/api/taurus/qt/qtgui/compact/_TaurusReadWriteSwitcher.html). For a quick test, you can simply launch `taurusform sys/tg_test/` and [change to it to "compact mode"](http://www.taurus-scada.org/en/latest/users/ui/forms.html?highlight=pending%20operations#compact-mode)

If you need more help on this, please open a separate issue

**Closed by cpascual** 2017-05-17 07:14 UTC
