### ISSUE TITLE
taurusuic4 error 

### ISSUE THREAD

**Issue by hayg25** [taurus-org/taurus#607] opened 2017-10-27 14:11 UTC
**taurusuic4 -x -o test01.py test01.ui**      
                                                                                               
Traceback (most recent call last):
  File "/usr/local/bin/taurusuic4", line 35, in <module>
    import taurus.qt.qtgui.util
  File "/usr/local/lib/python2.7/dist-packages/taurus/qt/__init__.py", line 30, in <module>
    from taurus.external import qt as __qt
  File "/usr/local/lib/python2.7/dist-packages/taurus/external/qt/__init__.py", line 102, in <module>
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1

**Comment by cpascual** [comment] 2017-10-30 08:39
Hi,

Which version of Taurus and PyQt4 are you using?
I cannot reproduce it with taurus 3.7.3 or  3.7.4 and PyQt 4.11

Still, you probably can work around this problem by editing the taurusuic4 script and replacing the line that says 
`import PyQt4.Qt as Qt` 
by 
`from taurus.external.qt import Qt`

(... or download and install the latest support-3.x branch, where this change is already done)

**IMPORTANT**: 
Please consider not using taurusuic4 at all. Note that taurusuic4 was deprecated since the introduction of [SEP11](https://github.com/sardana-org/sardana/blob/develop/doc/source/sep/SEP11.md) and while it is still present in taurus3.x, it was removed in taurus 4. The rationale can be read in the SEP11.
The alternative is to dynamically load the `.ui` files, either using the [UiLoadable API from taurus](http://www.taurus-scada.org/en/latest/devel/api/taurus/qt/qtgui/util.html#taurus.qt.qtgui.util.UILoadable) as suggested in SEP11, or [directly using the uic module(https://github.com/cpascual/pythoncourse-intermediate/blob/master/exercises/cheat/qtexercise2_uic.py))

**Comment by cpascual** [comment] 2017-11-09 09:03
Hi @hayg25 I assume that my answer above solved your issue, so I am closing this. Feel free to reopen if you need further help

**Closed** 2017-11-09 09:04 UTC
Labels: bug
