### ISSUE TITLE
PyQt GUI Hanged due to Attribute Polling Warning 

### ISSUE THREAD

**Issue by tcsgmrt** [taurus-org/taurus#462] opened 2017-06-12 12:02 UTC
Dear All,

I am facing GUI hang issue due to Attribute Polling Warning.It's show as message as below  :

```
**TimerLoop 1    WARNING  2017-06-12 16:56:06,055 TaurusPollingTimer[1000].Timer on _pollAttributes: loop function took more than loop interval (1.0s)**
**TimerLoop 1    ERROR    2017-06-12 16:56:08,591 TaurusPollingTimer[1000]: poll_reply error**
```

This is happen if one of device server disconnected from client.

Please help me to write handler for this exception.

Thanks,
HItesh Patel

**Comment by cpascual** [comment] 2017-06-12 12:31
First regarding the warning: 

The warning is a *consequence*, not a *cause* of a problem.
The warning basically is informing that one of the Taurus polling threads could not complete its polling in the requested time. 
Note that you are changing the standard polling time from 3s to 1s (thus this warning is more likely to happen)

Regarding the error:
As you say, it can be caused by some connection problem between the client and the device server.
In principle this should not occur (are you forcing the disconnection somehow?). Taurus (if not forced to do something else) takes care of retrying to connect in case of problems.
All you need to do is use Taurus' mechanisms for adding/removing listeners (instead of  PyTango's mechanisms). Also, consider handling error events in your wdget's handleEvent method (you can identify them via the evt_type argument).

**Comment by tcsgmrt** [comment] 2017-06-29 07:02
Dear Carlos,
Thanks for your valuable response.

we would like to know more about  Taurus' mechanisms for adding/removing listeners. I have noticed that tauruslabel does not affect GUI main thread if that device or attribute proxy device is disconnected.

In my case whole GUI is affected because we are using TANGO synchronous method to read the attribute using proxy.  Please Guide us on  Taurus' mechanisms for adding/removing listeners .

**Comment by cpascual** [comment] 2017-06-29 08:01
Ideally, when using Taurus you should not use PyTango directly (e.g. do not import PyTango). Also, even if (for backwards compatibility) taurus exposes some PyTango API in its TangoAttribute or TangoDevice objects, it is better to avoid using such PyTango API if possible.

If the existing Taurus widgets are not sufficient for your needs, the recommended way for creating a completely new Taurus Qt widget capable of subscribing to a Taurus Attribute (Taurus attributes may be Tango attributes, but also EPICS PVs or evals...) is to inherit both from a Qt widget (e.g. a QLabel) **and** from [TaurusBaseComponent](http://www.taurus-scada.org/en/latest/devel/api/taurus/qt/qtgui/base/_TaurusBaseComponent.html)  (or one of its subclasses). 

Then in your main program you call [setModel](http://www.taurus-scada.org/en/latest/devel/api/taurus/qt/qtgui/base/_TaurusBaseComponent.html#taurus.qt.qtgui.base.TaurusBaseComponent.setModelName) to associate the widget to an attribute. The TaurusBaseComponent provides all the infrastructure  for **automatically** handling subscription/unsubscription to the given attribute when setModel is called.

Once a model has been set on a taurus widget, the subscription happens behind the scenes and the widget gets notified of its model events via a complex chain of calls that start on the [eventReceived](http://www.taurus-scada.org/en/latest/devel/api/taurus/qt/qtgui/base/_TaurusBaseComponent.html#taurus.qt.qtgui.base.TaurusBaseComponent.eventReceived) callback and ends on [handleEvent](http://www.taurus-scada.org/en/latest/devel/api/taurus/qt/qtgui/base/_TaurusBaseComponent.html#taurus.qt.qtgui.base.TaurusBaseComponent.handleEvent). In most cases you do not need to worry about what goes on before `handleEvent`: you just need to reimplement `handleEvent` in your widget class to react to the events.

`handleEvent` will be invoked by taurus on each event with 3 args: 
- event source (typically the attribute object but it could be None in some cases, or another TaurusModel object if the widget is a listener of more than one model at a time)
- the event type (one of the possible [TaurusEventType](http://www.taurus-scada.org/en/latest/_modules/taurus/core/taurusbasetypes.html?highlight=TaurusEventType) enum values) 
- the event value (in the case of `Change` or `Periodic` events, this is equivalent to what you would get if you had called the `read()` method of a `TaurusAttribute`, in the case of an `Error` event it will be an `Exception` object)

For a practical example, see [this exercise](https://github.com/ap--/python-seabreeze/blob/master/docs/DOCUMENTATION.md) and its [solution](https://github.com/cpascual/pythoncourse-intermediate/blob/master/exercises/cheat/taurusexercise2.py)

I hope this helps (I think I will propose to include this explanation in the official docs)

PS: in my discussion I mentioned attributes (because they send events), but a similar procedure can be used for devices...

**Comment by cpascual** [comment] 2017-07-05 11:55
@tcsgmrt : is [this question in the Tango forums](http://www.tango-controls.org/community/forum/post/2724/) related to this issue? If so, did you try the approach that I mention in my previous reply?

**Comment by tcsgmrt** [comment] 2017-07-07 13:48
Dear Carlos,

Thanks for your suggestion. our application is already developed and it will be very difficult modify our code according to your suggestion. So currently we are trying to implement using Qthread to offload GUI main thread so we can resolve the freeze issue.  
while using Qthread for creating tauruslabel and pass it to main GUI thread we have following error.

**TaurusRootLogger : Qt : QCoreApplication::sendPostedEvents : Cannot send posted events for objects in another thread.**      

In application we have to create minimum of 1000 of tauruslabel  so we thought that is we can create that tauruslabel in Qthread and add it to main GUI .

To create Qthread and QObject we have used following approach.
            self.get_thread = QThreads()
            self.Worker =  Worker()
            self.Worker.moveToThread(self.get_thread)


class Worker(QtCore.QObject):
      def __init__(self):
            super(Worker,self).__init__(self)

please help us if you have any idea about how to create GUI object in one thread and pass it to Main GUI thread.

Thanks,
Hitesh Patel

**Comment by cpascual** [comment] 2017-07-10 10:56
Hi @tcsgmrt I am afraid that your problem is not taurus-specific .Even if the log message is delivered by the Taurus logging system, the cause of the error is pure Qt, so you will need to seek advice on that on (Py)Qt resources.

Also, the original question seems to be answered, so I am closing this . If you have other questions, please open independent issues.

**Closed by cpascual** 2017-07-10 10:56 UTC
Labels: question
