### ISSUE TITLE
taurusdesigner sometimes produces "----" for taurusLabel text

### ISSUE THREAD

**Issue by CorF4** [taurus-org/taurus#720] opened 2018-03-05 14:07 UTC
Hello,
upon updating to taurus-4.3.0 I found that sometimes the taurusLabel displays "----" as text constantly. I have produced the widget via the taurusdesigner. It seems that for some reason sometimes this ends up in the produced ui-file:

```
<property name="text">
<string>----</string>
</property>
```

In the previous version of taurus that I used (4.1.1) this was not an issue, now it seems I have to manually remove this from the ui-file to make it work. 
When is this produced in the ui-file? Seems a bit random to me. In principle, once the ui-file is finalised, it is not a big problem to remove these lines, but just a bit of a nuisance.
Thanks for giving any insights!

**Comment by cpascual** [comment] 2018-03-05 22:15
Can you please post a minimal example of a .ui file (and let us know step-by-step how you created it with designer) so that we can try to reproduce it?

Also, are you setting models in the designer? (while officially allowed, this sometimes causes issues, -especially if the DSs are not reachable- and we generally discourage it)

**Comment by CorF4** [comment] 2018-03-06 08:46
Hi, the reproducability is actually part of the problem. I don't know when this ends up in the ui-file. I have a Form with many taurusLabels, and for some reason, only one of them had this property set in the ui-file.
I can post a minimal example, but here I manually added the problematic lines. 
(What I did: created an empty Form, added a taurusFrame, added a taurusLabel, set model of this label to /State, set 'useparentModel'.)
It may be that this has nothing to do with taurus at all, but the previous version was ignoring it and it didn't show up when running the gui.

I set the model only later when I launch the python script that invokes this ui-file.

```
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>Form</class>
 <widget class="QWidget" name="Form">
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>400</width>
    <height>126</height>
   </rect>
  </property>
  <property name="windowTitle">
   <string>Form</string>
  </property>
  <widget class="TaurusFrame" name="taurusFrame">
   <property name="geometry">
    <rect>
     <x>50</x>
     <y>30</y>
     <width>321</width>
     <height>81</height>
    </rect>
   </property>
   <widget class="TaurusLabel" name="taurusLabel">
    <property name="geometry">
     <rect>
      <x>80</x>
      <y>20</y>
      <width>201</width>
      <height>31</height>
     </rect>
    </property>
    <property name="model">
     <string>/State</string>
    </property>
    <property name="useParentModel">
     <bool>true</bool>
    </property>
    <property name="bgRole">
     <string>quality</string>
    </property>
    <property name="text">
     <string>----</string>
    </property>
   </widget>
  </widget>
 </widget>
 <customwidgets>
  <customwidget>
   <class>TaurusFrame</class>
   <extends>QFrame</extends>
   <header>taurus.qt.qtgui.container</header>
   <container>1</container>
  </customwidget>
  <customwidget>
   <class>TaurusLabel</class>
   <extends>QLabel</extends>
   <header>taurus.qt.qtgui.display</header>
  </customwidget>
 </customwidgets>
 <resources/>
 <connections/>
</ui>
```

and the script:
```
import sys
from taurus.external.qt import Qt
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.util.ui import UILoadable

@UILoadable
class test(Qt.QWidget):
   
def __init__(self, model=None, parent=None):
        Qt.QWidget.__init__(self, parent)

        self.loadUi()

        self.taurusFrame.setModel(model)
        
if __name__ == '__main__':
    
    instance = sys.argv[1]
    
    from taurus.qt.qtgui.application import TaurusApplication
    from taurus.qt.qtgui.taurusgui import TaurusGui
    from taurus.external.qt import Qt
    app = TaurusApplication(app_name='MyGui')
    panel = test(model=instance)
    panel.show()
    app.exec_()
```
That takes the model name as an argument.

For me it would be interesting to know, if others that use a ui-file, also observe something like this or if there is a known pattern that causes this behaviour.

**Comment by CorF4** [comment] 2018-03-06 12:08
Somehow self.taurusLabel.setModel(model) ("taurusLabel" is widget name) doesn't seem to work...

**Comment by cpascual** [comment] 2018-06-05 15:42
We just got an internal report at ALBA of this exact same problem. But unfortunately we could not reproduce it either. But the "post-mortem" analysis points to an ui created with an early taurus 4.1 (or maybe even 3.7) which was later on edited with a different version...

But as I said, I could not reproduce it with the current version.

**Comment by cpascual** [comment] 2018-07-02 15:28
Hi, I am closing this but since we can't reproduce it and it seems related to old versions. Please reopen if you can reproduce it with a recent version.

**Closed by cpascual** 2018-07-02 15:28 UTC
Labels: bug
