### ISSUE TITLE
TaurusValuesTable cannot be used with "useParentModel"

### ISSUE THREAD

**Issue by mkomel** [taurus-org/taurus#676] opened 2018-01-26 09:55 UTC
When using TaurusValuesTable (TaurusQT) with "useParentModel=true", I get the following error:
  

> File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 256, in createWidget
>     self.stack.push(self.setupObject(widget_class, parent, elem))
>   File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 222, in setupObject
>     self.wprops.setProperties(obj, branch)
>   File "/usr/lib/python2.7/dist-packages/PyQt4/uic/properties.py", line 422, in setProperties
>     getattr(widget, 'set%s%s' % (ascii_upper(prop_name[0]), prop_name[1:]))(prop_value)
>   File "/usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/table/taurusvaluestable.py", line 672, in setModel
>     if model_obj.isWritable() and self.defaultWriteMode != "r":
> AttributeError: 'NoneType' object has no attribute 'isWritable'

Using full model on the widget (without useParentModel) does not give this error, though.

**Comment by cmft** [comment] 2018-01-26 15:07
Hi @mkomel ,
Which parent widget are you using?, Can you attach us your code?

**Comment by mkomel** [comment] 2018-01-27 16:37
Hi @cmft ,

I'm using TaurusFrame.

I have created a small example. Main python file uses a ui file named SandboxWidget.ui, which must be placed in a subfolder named "ui". Running this example will result in an error:
`AttributeError: 'NoneType' object has no attribute 'isWritable'`
By changing the ui file so that the TaurusValuesTable within has `useParentModel=False`, and `model=sys/tg_test/1/double_spectrum`, the error will be gone.


Main python file:
```
import sys
from taurus.external.qt import Qt, QtCore
from taurus.qt.qtgui.util.ui import UILoadable
from taurus.qt.qtgui.application import TaurusApplication

@UILoadable
class SandboxWidget(Qt.QWidget):
	def __init__(self, model, parent=None):
		Qt.QWidget.__init__(self, parent)
                self.loadUi()
                self.taurusFrame.model = model

if __name__ == "__main__":
		
        model = "sys/tg_test/1"

	app = TaurusApplication(app_name='not_working')
	panel = SandboxWidget(model)
	panel.show()
	app.exec_()
```

SandboxWidget.ui file:
```
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>widget</class>
 <widget class="QWidget" name="widget">
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>407</width>
    <height>485</height>
   </rect>
  </property>
  <property name="windowTitle">
   <string>Sandbox panel</string>
  </property>
  <widget class="TaurusFrame" name="taurusFrame">
   <property name="geometry">
    <rect>
     <x>20</x>
     <y>40</y>
     <width>351</width>
     <height>401</height>
    </rect>
   </property>
   <widget class="TaurusLabel" name="taurusLabel_2">
    <property name="geometry">
     <rect>
      <x>40</x>
      <y>20</y>
      <width>121</width>
      <height>19</height>
     </rect>
    </property>
    <property name="model">
     <string>/double_scalar</string>
    </property>
    <property name="useParentModel">
     <bool>true</bool>
    </property>
    <property name="modelIndex">
     <string/>
    </property>
   </widget>
   <widget class="TaurusValuesTable" name="taurusValuesTable">
    <property name="geometry">
     <rect>
      <x>40</x>
      <y>60</y>
      <width>274</width>
      <height>304</height>
     </rect>
    </property>
    <property name="useParentModel">
     <bool>true</bool>
    </property>
    <property name="modifiableByUser">
     <bool>false</bool>
    </property>
    <property name="model">
     <string>/double_spectrum</string>
    </property>
    <property name="writeMode">
     <bool>false</bool>
    </property>
   </widget>
  </widget>
 </widget>
 <customwidgets>
  <customwidget>
   <class>TaurusFrame</class>
   <extends>QFrame</extends>
   <header>taurus.qt.qtgui.container</header>
   <container>1</container>
  </customwidget>
  <customwidget>
   <class>TaurusWidget</class>
   <extends>QWidget</extends>
   <header>taurus.qt.qtgui.container</header>
   <container>1</container>
  </customwidget>
  <customwidget>
   <class>TaurusLabel</class>
   <extends>QLabel</extends>
   <header>taurus.qt.qtgui.display</header>
  </customwidget>
  <customwidget>
   <class>TaurusValuesTable</class>
   <extends>TaurusWidget</extends>
   <header>taurus.qt.qtgui.table</header>
   <container>1</container>
  </customwidget>
 </customwidgets>
 <resources/>
 <connections/>
</ui>
```

**Comment by mkomel** [comment] 2018-01-27 16:45
If everything is done in code (without using .ui file), it works fine (see below for an example).
However, I found one additional problem (bug) with the TaurusValuesTable. Try changing `valuestable.model = "/short_spectrum"` to `valuestable.model = "/short_spectrum_notexisting"` in this example. It will result in an error with a program crash (so, as soon as a non-existing or non-accessible attribute is used with the TaurusValuesTable, this will happen):
`Exception: rvalue is invalid`

```
import sys
from taurus.external.qt import Qt, QtCore
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.container import TaurusFrame
from taurus.qt.qtgui.display import TaurusLabel
from taurus.qt.qtgui.table import TaurusValuesTable

if __name__ == "__main__":

    app = TaurusApplication(app_name='sandbox')
    panel = Qt.QWidget()

    frame = TaurusFrame(panel)
    frame.resize(500,500)
    frame.model = "sys/tg_test/1"

    label = TaurusLabel(frame)
    label.resize(100,20)
    label.move(50, 25)
    label.useParentModel = True
    label.model = "/double_scalar"

    valuestable = TaurusValuesTable(frame)
    valuestable.move(50,50)
    valuestable.useParentModel = True
    valuestable.model = "/short_spectrum"

    panel.show()
    app.exec_()

```

**Comment by cmft** [comment] 2018-01-29 08:28
Hi @mkomel ,
Many thanks for this help.

The  first error is related with compose the model (CONFIRMED)
- using useParentModel in the ui file seems to not work
- and taurusvaluestable is not protected against "wrong" models

The second error:
I got an exception (my gui did not start), looking at the code this is due to taurusvaluestable try to configure itself depending if the attribute is 1D or 2D, but since the attribute did not exist , it raises the exception.
```
 python test2.py 
MainThread     INFO     2018-01-29 09:21:47,479 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2018-01-29 09:21:47,810 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/icon/)
MainThread     WARNING  2018-01-29 09:21:48,173 controls01:10000.sys/tg_test/1.state: Unknown unit "No unit (will be treated as unitless)"
Traceback (most recent call last):
  File "test2.py", line 26, in <module>
    valuestable.model = "/short_spectrum2"
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/table/taurusvaluestable.py", line 707, in setModel
    raise Exception('rvalue is invalid')
Exception: rvalue is invalid

```

We will work on that.

**Comment by cpascual** [comment] 2018-01-29 08:35
> If everything is done in code (without using .ui file), it works fine

This makes me suspect that you are hit by the known limitation described in the [TaurusBaseWidget.recheckTaurusParent docs](http://www.taurus-scada.org/en/latest/devel/api/taurus/qt/qtgui/base/_TaurusBaseWidget.html?highlight=recheckTaurusParent#taurus.qt.qtgui.base.TaurusBaseWidget.recheckTaurusParent). Please have a look also at the [parentmodel_issue_demo.py](http://www.taurus-scada.org/en/latest/_downloads/parentmodel_issue_demo.py)

**Comment by cpascual** [comment] 2018-01-29 08:37
> using useParentModel in the ui file seems to not work

As the links in my previous comments point out, this can be worked around by calling `recheckTaurusParent()`

**Comment by mkomel** [comment] 2018-01-29 08:52
I have tried to do `self.taurusValuesTable.recheckTaurusParent()`  in my first example above (the one with the .ui file).  It didn't help, the problem persists.
Note that there is also a TaurusLabel in that example, and that widget does not suffer the same problem as TaurusValuesTable (e.g. if you remove the TaurusValuesTable, or if you use it with a full model (with useParentModel=false), you will see that the TaurusLabel loads fine). Since those two are parented exactly the same, I guess this demonstrates that there is a unique problem there only with the TaurusValuesTable.

**Comment by cpascual** [comment] 2018-01-29 09:20
Ok. Then I guess that the difference with TaurusLabel is that the TaurusValuesTable may be itself using a more complex arrangement of subwidgets (some of them taurus, some of them pure-Qt) and therefore it may be affected by the parentmodel issue internally (i.e. not properly supporting the parent model feature).

I **personally** have always avoided using the parent model anyway... (and I would advocate to get rid of the feature...)

**Comment by dvucko** [comment] 2018-03-06 23:31
I tried this with taurus 4.3.0 and the issue persists.

A simple fix to solve this at least partially is to do the following in `taurusvaluestable.py`:

- in `setModel(self, model)`, move the entire `if model_obj.isWritable()  ...` block inside the `if model_obj is not None:` to get rid of the `isWritable` error mentioned by the OP:
```
    def setModel(self, model):
        '''Reimplemented from :meth:`TaurusWidget.setModel`'''
        TaurusWidget.setModel(self, model)
        model_obj = self.getModelObj()

        if model_obj is not None:
            if model_obj.isWritable() and self.defaultWriteMode != "r":
                self._writeMode = True
            else:
                self.defaultWriteMode = "r"
        ...
```

- to display the selected model correctly, add the following check to the beginning of `def handleEvent(self, evt_src, evt_type, evt_value)`:
```
        if not self._updatedModelOnce and self.useParentModel:
            self.setModel(self.model)
            self._updatedModelOnce = True
```
where `self._updatedModelOnce` is an instance attribute defined in `__init__` and initialized to false. This is done to prevent re-setting the model on each event, thus making it possible to enter new values in write mode.

Obviously, this is more of a hack than a proper solution. Moreover, there are other issues: for example, if a nonexistent model is set, the visual style (style sheet) of the TaurusValuesTable will not be changed to reflect the erroneous state. In contrast, the visual style of e.g. TaurusLabel and TaurusLCD will in such case be automatically changed (greyed out), notifying the user that something is wrong.

**Comment by cpascual** [comment] 2018-04-20 07:57
Hi @dvucko , thanks for the suggestion. While personally I advocate for [deprecating the useParentModel feature](#732), I think that if it does not break anything else, your workaround is worth implementing in the meanwhile. So, would you care to create a PR with it? (please see the [CONTRIBUTING](https://github.com/taurus-org/taurus/blob/develop/CONTRIBUTING.md) file if you need some guidelines)

**Comment by dvucko** [comment] 2018-05-16 12:01
@cpascual I'm inclined to agree with your position of deprecating the feature, all things considered. Regarding the proposed fix/hack, I'm not particularly comfortable to submit it, because there might be potential undetected side effects that I'm not aware of. I might do it in the future after more testing, if that is OK.

**Comment by cpascual** [comment] 2019-07-01 08:33
Closing as won't fix since it affects a deprecated feature

**Closed by cpascual** 2019-07-01 08:33 UTC
Labels: bug
