### ISSUE TITLE
TaurusCommandButton not getting connected

### ISSUE THREAD

**Issue by mkomel** [taurus-org/taurus#828] opened 2018-11-14 17:01 UTC
There seems to be a problem with TaurusCommandButton widget. 
If the taurus gui with more than one TaurusCommandButton is started before the device server is started, only the first button gets eventually connected when the device server is started. All other buttons remain in an unconnected state.

Tested with taurus 4.4.0:
```

from taurus.external.qt import Qt, QtCore
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.container import TaurusFrame
from taurus.qt.qtgui.button import TaurusCommandButton

if __name__ == '__main__':
        app = TaurusApplication(app_name = 'MyGui')
        panel = Qt.QWidget()

        frame = TaurusFrame(panel)
        frame.resize(200,200)
        
        button1 = TaurusCommandButton(frame)
        button1.move(50,50)
        button1.setModel("sys/tg_test/1")
        button1.setCommand("SwitchStates")

        button2 = TaurusCommandButton(frame)
        button2.move(50,100)
        button2.setModel("sys/tg_test/1")
        button2.setCommand("DevVoid")

        panel.show()
        app.exec_()
```

This seems to be related to #791, but note that here useParentModel is not used.

**Comment by cpascual** [comment] 2018-11-15 13:49
>This seems to be related to #791, but note that here useParentModel is not used.

I am quite certain that this is indeed a duplicate of #791
Note that, as I showed in the snippet in https://github.com/taurus-org/taurus/issues/791#issuecomment-413485346 , `useParentModel` is not required to reproduce it.

#792 fixed this in the develop branch. If you need this fixed before the next official release you can either use the develop branch or just apply the [patch of #792](https://github.com/taurus-org/taurus/pull/792.patch)

**Closed by cpascual** 2018-11-15 13:49 UTC
Labels: duplicate, rejected

**Comment by mkomel** [comment] 2018-11-15 14:04
Oh yes, indeed.  Sorry about this duplicate report.

When writing this issue I actually thought that it was related to another issue - #732 ,  but  when writing the issue report I somehow (mistakenly) managed to refer it to the correct one #791 (not sure how) without really realizing that that the 791 exactly reports my issue, by my colleague actually.   
Must have been due to a long day in the office :)
