### ISSUE TITLE
popup menu of embedded Qt widget

### ISSUE THREAD

**Issue by kklmn** [taurus-org/taurus#910] opened 2019-05-05 16:56 UTC
Hello,

I embed a custom Qt widget into Taurus Gui. The problem is that its popup menu is gone and replaced by "macro execution configuration..." menu. When I detach the widget from the main gui, the menu is back.

How can I retain the native menu?

Thanks!

**Comment by cmft** [comment] 2019-05-06 06:23
Hi @kklmn,
Maybe you are affected by #906.

**Comment by kklmn** [comment] 2019-05-06 09:54
Looks like it is it. Can I do something with it?

**Comment by cpascual** [comment] 2019-05-06 10:11
@cmft is quite certainly right. #906 is already integrated in develop, so you can confirm by trying with taurus from the develop branch

**Comment by cpascual** [comment] 2019-05-21 06:18
Hi @kklmn can you confirm if the fix of #906 solved your issue (so that we can close this issue)

**Comment by kklmn** [comment] 2019-05-21 07:19
Hi,
I've installed now taurus locally and created a simple tuarusgui but can't start it, which is a serious issue per se. Specifically, it wants the non-local version of taurus (which is older) via sardana:
```
  File "./taurusgui.py", line 1135, in loadConfiguration
    from sardana.taurus.qt.qtgui.macrolistener import MacroBroker
```
So I can't confirm the issue with popup menu is solved.

**Comment by cpascual** [comment] 2019-05-21 08:35
Hi @kklmn , thanks for the quick reply

I am not sure I understand the problem you are having. In my system, with taurus and sardana both installed from their develop branches, I just ran 
`from sardana.taurus.qt.qtgui.macrolistener import MacroBroker` and I got no issues.

Maybe this is a problem of having both versions of taurus and/or sardana interfering with each other? If so, maybe using a virtualenv or a conda environment (or the [taurus-test docker image](https://github.com/cpascual/taurus-test) could help to test this in isolation?

If the above does not help, can you please provide more details so that we can try to reproduce your issue?

**Comment by kklmn** [comment] 2019-05-21 08:42
I am speaking about a local installation (with --user by pip). This installation can't be used because it imports sardana that imports taurus (non-local)

**Comment by cpascual** [comment] 2019-07-01 07:43
Hi @kklmn ,  since our tests indicate that this is solved and you cannot do more tests for now, I am closing this for as fixed. If you manage to reproduce the problem with the latest develop branches, feel free to reopen.

**Closed by cpascual** 2019-07-01 07:43 UTC
