### ISSUE TITLE
Taurusform --default-formatter param: default sets mbar, V etc; tango sets milibar, volts etc;

### ISSUE THREAD

**Issue by MikeFalowski** [taurus-org/taurus#746] opened 2018-05-02 09:00 UTC
If taurusform run with:

1.  without `--default-formatter` units are showed as defined in attribute config (mbar, V, etc.)
2.  without `--default-formatter` but tango formatter set with `Set formatter` it also shows  mbar, V, etc.
3.  `--default-formatter=...tango` shows long unit names
4.  `--default-formatter=...tango` but default formatter set with `Set formatter` still show long names

Changing units from `mbar` to `V` in Jive attribute config cause `milibar` to `volts` change in two last configurations.

**Comment by cpascual** [comment] 2018-05-02 14:12
I think that this is a duplicate of #647 
Specifically, see https://github.com/taurus-org/taurus/issues/647#issuecomment-352398460 for a workaround.

(I am closing. Feel free to reopen if you do not consider that this is a duplicate)

**Closed by cpascual** 2018-05-02 14:12 UTC

**Comment by cpascual** [comment] 2018-05-02 14:14
As a general rule: avoid using `--default-formatter` argument since it its too indiscriminate (it affects **all** widgets in the application, and this is generally *not* what you want)
