### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PYQT_QSTRING_API_1' for PyQt5

### ISSUE THREAD

**Issue by jkotan** [taurus-org/taurus#837] opened 2019-01-09 14:59 UTC
Hi,

When I what to test taurus with PyQt5 by setting
```python
import os
os.environ['DEFAULT_QT_API'] = 'pyqt5'
os.environ['QT_API'] = 'pyqt5'
```

I get the following error:

```
MainThread     INFO     2019-01-09 15:54:37,277 TaurusRootLogger: Using "PyQt5" for Qt
Traceback (most recent call last):
  File "./lavuetaurus", line 42, in <module>
    from taurus.qt.qtgui.base import TaurusBaseWidget
  File "/usr/lib/python2.7/dist-packages/taurus/qt/qtgui/__init__.py", line 35, in <module>
    import icon as __icon
  File "/usr/lib/python2.7/dist-packages/taurus/qt/qtgui/icon/__init__.py", line 32, in <module>
    from catalog import QIconCatalog
  File "/usr/lib/python2.7/dist-packages/taurus/qt/qtgui/icon/catalog.py", line 31, in <module>
    from taurus.qt.qtgui.input import GraphicalChoiceWidget
  File "/usr/lib/python2.7/dist-packages/taurus/qt/qtgui/input/__init__.py", line 32, in <module>
    from .tauruscheckbox import *
  File "/usr/lib/python2.7/dist-packages/taurus/qt/qtgui/input/tauruscheckbox.py", line 33, in <module>
    from taurus.qt.qtgui.base import TaurusBaseWritableWidget
  File "/usr/lib/python2.7/dist-packages/taurus/qt/qtgui/base/__init__.py", line 31, in <module>
    from .taurusbase import *
  File "/usr/lib/python2.7/dist-packages/taurus/qt/qtgui/base/taurusbase.py", line 57, in <module>
    from taurus.qt.qtgui.util import ActionFactory
  File "/usr/lib/python2.7/dist-packages/taurus/qt/qtgui/util/__init__.py", line 38, in <module>
    from .validator import *
  File "/usr/lib/python2.7/dist-packages/taurus/qt/qtgui/util/validator.py", line 31, in <module>
    class PintValidator(Qt.QValidator):
  File "/usr/lib/python2.7/dist-packages/taurus/qt/qtgui/util/validator.py", line 123, in PintValidator
    validate = Qt.PYQT_QSTRING_API_1 and _validate_oldQt or _validate
AttributeError: 'module' object has no attribute 'PYQT_QSTRING_API_1'
```
It looks like for pyqt5 `PYQT_QSTRING_API_1` is not defined but it is used.
The same code with `pyqt4` works fine.

Is there any other way to use pyqt5 iwth taurus when both qt4 and qt5 are installed?

**Comment by reszelaz** [comment] 2019-01-09 15:06
> Is there any other way to use pyqt5 iwth taurus when both qt4 and qt5 are installed?

Works on adapting Taurus for PyQt5 are done in #814. You will need to wait until Jan19 release for that.

**Comment by cpascual** [comment] 2019-01-09 16:22
> You will need to wait until Jan19 release for that.

... or use the [tep18](https://github.com/cpascual/taurus/tree/tep18) branch and help us find its bugs before they creep into the jan19 release! ;-)

Right now, I would say that most stuff is already working in tep18 branch (see #830)

PS: I close this one as duplicate of #814 , #203

**Closed by cpascual** 2019-01-09 16:22 UTC

**Comment by jkotan** [comment] 2019-01-09 17:58
Thanks.
