### ISSUE TITLE
Taurus Attribute ignoring Tango events: change not found in event callback map?

### ISSUE THREAD

**Issue by sergirubio** [taurus-org/taurus#485] opened 2017-07-04 09:24 UTC
Hi, 

I've noticed that TaurusTrend was not updating an attribute at the same speed that events were generated. I've tried again from shell and PyTango is receiving the events; but Taurus seems to ignore them (see attached screenshot with logs).

The error printed by Taurus is:
![screenshot from 2017-07-04 11-09-52](https://user-images.githubusercontent.com/18418345/27823891-f8acae4e-60aa-11e7-9dad-efd1344ccb05.png)
Tue Jul  4 11:20:52 2017: Event tango://wiusb05.cells.es:10000/sys/tg_test/1/double_scalar.idl5_change not found in event callback map !!!

To reproduce the bug I configured events on TangoTest double_scalar attribute and executed these two codes in python using raw PyTango or Taurus (Debian 9, PyTango 9.2.0, Taurus 4.0.4-alpha).

CODE USING PYTANGO
```
import PyTango,time
dev = 'sys/tg_test/1'
attr = 'double_scalar'
dp = PyTango.DeviceProxy(dev)
ac = dp.get_attribute_config(attr)
ac.events.ch_event.abs_change = '0.0001'
ac.events.ch_event.rel_change = '0.0001'
dp.set_attribute_config(ac)
dp.poll_attribute(attr,2000)
tt = [time.time()]
def cb(*args):
    p,tt[0] = tt[0],time.time()
    print(tt[0]-p)
ei = dp.subscribe_event(attr,PyTango.EventType.CHANGE_EVENT,cb)
```

CODE USING TAURUS:

  taurustrend sys/tg_test/1/double_scalar

or
```
import time,taurus
dev = 'sys/tg_test/1'
attr = 'double_scalar'
ta = taurus.Attribute(dev+'/'+attr)
tt = [time.time()]
def cb(*args):
    p,tt[0] = tt[0],time.time()
    print(tt[0]-p)
ta.addListener(cb)
```

**Comment by cmft** [comment] 2017-07-05 06:36
Hi @sergirubio ,
I can not reproduce the error (with the attached code) when I attack a Tango9 db
PyTango Test:
```
0.0273740291595

In [2]: 1.07545113564
2.00011587143
2.00013589859
2.00014901161
2.00016307831
2.00013303757
1.99913907051
2.00014591217
2.00007891655
2.00016903877
2.00009608269
2.00017595291
2.00014400482
1.99913907051
2.00015592575
2.00013709068
2.00013899803
2.00010490417
2.00015592575
```
Taurus Test:
```
0.0106670856476
Out[1]: True

In [2]: 0.403913021088
1.99921679497
2.00014019012
2.00013494492
2.00014686584
2.00013303757
2.00013899803
2.00010204315
1.99917292595
2.00013709068
2.00014305115
2.00014400482

```
I see more different between times in both clients when a tango7 db is used, but I don't see the event errors:

PyTango Test:
```
0.0507428646088

In [13]: 1.25840520859
1.97938680649
2.00063610077
1.39945006371
2.00439381599
1.99953722954
3.39522886276
1.9999499321
1.999958992
2.00005221367
1.40043282509
1.99980711937
1.99991989136
1.99969696999
3.39947319031
2.00035881996
1.99954295158
1.40039920807
1.99985790253
2.00054192543
1.99963498116
1.39976000786
1.99924397469
4.00048899651
1.40041518211

``` 

Taurus Test:
```                                                                                                                                                      
0.0160701274872                                                                                                                                                                    
Out[7]: True    
In [8]: 0.516788959503
3.00179600716    
2.99800992012     
4.40272903442     
3.00032806396     
1.40099406242     
2.9998729229      
3.00074100494     
4.40106987953     
3.00145506859     
1.40134596825     
2.99950814247     
3.00024294853     
1.40164494514     
3.01255011559     
2.98800086975     
4.40111708641     
3.00088191032     
1.40127301216     
2.99950408936     
3.00051593781
4.40237092972
2.99980807304
1.40255403519
2.9996099472
3.00020003319
1.40153098106
2.99994802475
2.99994587898
1.40233707428
3.00010108948
2.99915790558
1.40240311623
2.99943900108
 
```

**Comment by sergirubio** [comment] 2017-07-05 08:14
I think there's a problem on how Taurus is fixing the URI for this device. In the error the host appears as 'wiusb05'; when its real name is pt143 (or localhost).
It seems that the wifi is messing up with the hostname, but it affects only Taurus and not raw PyTango.
Could you try to replicate it with a laptop on cells wifi network?
Sergi

**Comment by sergirubio** [comment] 2017-07-05 08:31
Well, solved somehow.

The automated tango-db installation failed when I tried to set a hostname different from the wifi-assigned name; so I had to use localhost:10000.

But, once the system is running, having a TANGO_HOST like localhost:10000 seems to mess up with taurus.

I forced a fixed HOSTNAME value on this machine and used this host as TANGO_HOST value in /etc/tangorc. Now it works.

You may add a warning somewhere to avoid setting TANGO_HOST=localhost:10000 and close this issue.

Sergi

**Comment by cpascual** [comment] 2017-07-05 11:17
Hi @sergirubio ,
Thanks for the explanation. I am closing the issue since it is solved.
About adding a note to avoid `localhost`, IMHO this is a network configuration / Tango issue, not Taurus so I do not see where we could mention this. If you have some idea, please do a PR.

**Closed by cpascual** 2017-07-05 11:17 UTC
Labels: rejected

**Comment by sergirubio** [comment] 2017-07-05 12:25
Well, the issue didn't affected PyTango, only taurus.

**Comment by reszelaz** [comment] 2017-07-05 13:06
sergirubio:
> Well, the issue didn't affected PyTango, only taurus.

I recall having a similar problem some time ago on my Windows laptop. Initially, I was also "blaming" Taurus for the events' problems. But it appeared that the same problem was also affecting PyTango.
The thing is that the Taurus, behind the scenes, is creating a DeviceProxy with the full name i.e.`<db_host>:<db_port>/` prepended to the device name (even if you create a taurus Device with just the device name). In your example, you set the device name: `sys/tg_test/1`. I have a suspicion that if you use `localhost:10000/sys/tg_test/1` you would get the same problem with PyTango.

**Comment by sergirubio** [comment] 2017-07-05 13:41
ok, that makes sense. issue closed
