### ISSUE TITLE
slot setModel from TaurusImageDIalog is not exposed to qtdesigner

### ISSUE THREAD

**Issue by vallsv** [taurus-org/taurus#1023] opened 2019-11-06 17:10 UTC
Hi,

I try to upgrade a 5 years old application:
- from Python 2.6 to Python 2.7
- from Qt4 to Qt5
- from Taurus 3.4 to Taurus 4.5.1

I use to use a lot qt designer, and signals.

Unfortunately it looks like things are broken, but i can't really explain why.

My script are rejected when it tries to connect a string signal to `setModel` of `TaurusImageDialog`. I use python scripts with qtdesigner files to describe signal connections.

`setModel` looks to be correctly tagged.
```
    @Qt.pyqtSlot(str)
    def setModel(self, model):
```

But in Qt designer (`taurusdesigner`) the `setModel` slot is not exposed.

![taurus-taurusimagedialog-setmodel](https://user-images.githubusercontent.com/7579321/68320021-89455f80-00bf-11ea-980e-acb1831e28e5.png)

Any idea why?
Thanks a lot.

(yet i only try Taurus 4.5.1 version, but i guess i could use the last release without problem)

**Comment by cpascual** [comment] 2019-11-07 10:49
Hi, I am afraid that you found a regression that was quite likely introduced when we started supporting py2 and py3 simultaneously. We did not notice it because it works well in Python3.

As a workaround, if you replace the  `@Qt.pyqtSlot(str)`, by `@Qt.pyqtSlot("QString")` it should work. I submitted this fix as PR #1024

PS: The next official release of Taurus (planned for January 2020) will probably be the last supporting python2 . So maybe, given that you are upgrading, you could consider also moving to python >=3.5

**Comment by vallsv** [comment] 2019-11-07 11:18
Oh... Thanks for the feedback.

I have to check, all this things, and other regressions with slots and QString then; i already have patched a lot of it on my one base code (QString -> str).

Your discover is already very useful. I will try to check the `pyqtSlot` implementation. It could be really convenient to patch it for Python2. I don't have problem to apply this kind of patch on my project side. Then, If you prefer not to apply this #1024 i am fine with it, cause there is for sure other slot and QString to update. And i think it is better to stay with a Python3 code base. But it's up to you.

I would love to upgrade to Python3, but that's a big step. I don't think i will have the time.

**Comment by cpascual** [comment] 2019-11-07 14:41
> If you prefer not to apply this #1024 i am fine with it

No, do not worry. Using `"QString"` instead of `str` in `pyqtSlot`  is the right way to go for *both* py2 and py3 (note that  `"QString"` is a *string*, not the deprecated `QString` class), and it is what we have all around in taurus. So we are interested in merging #1024 anyway.

**Comment by vallsv** [comment] 2019-11-07 16:17
Oh, ok then. That's good, cause i am still stuck to monkey patch this Qt decorator.

**Closed** 2019-11-26 15:32 UTC
Labels: bug, py3
