### ISSUE TITLE
taurus newgui reports an error with Taurus4 + Python3

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#1017] opened 2019-10-03 10:57 UTC
taurus newgui reports an error with Taurus4.6.1 + Python3 

Reproducible with:
`taurus newgui`

It happens both with pyqt4 and pyqt5

```

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sardana/taurus/core/tango/sardana/macroserver.py", line 839, in on_environment_changed
    return self._on_environment_changed(evt_src, evt_type, evt_value)
  File "/usr/lib/python3/dist-packages/sardana/taurus/core/tango/sardana/macroserver.py", line 850, in _on_environment_changed
    env = CodecFactory().decode(evt_value.value)
  File "/usr/lib/python3/dist-packages/taurus/core/util/codecs.py", line 999, in decode
    data = self.getCodec(data[0]).decode(data, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/taurus/core/util/codecs.py", line 295, in decode
    return format, pickle.loads(data[1])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdb in position 0: ordinal not in range(128)
```

**Comment by cpascual** [comment] 2019-10-04 07:44
I cannot reproduce it with current develop branch of taurus  (v4.6.2a):

Can you please try with it?

**Comment by mrosanes** [comment] 2019-10-04 08:06
With develop at v4.6.2a I still have the error in sicilia@pcbl0906

**Comment by mrosanes** [comment] 2019-10-04 16:40
File "/usr/lib/python3/dist-packages/sardana/taurus/core/tango/sardana/macroserver.py", line 839...

Most probably is happening because the sardana servers are in suse11-Python2, and the Taurus client is in Debian9-Python3.

**Comment by cpascual** [comment] 2019-10-07 07:55
> File "/usr/lib/python3/dist-packages/sardana/taurus/core/tango/sardana/macroserver.py", line 839...

That means it is in sardana (not taurus)

>Most probably is happening because the sardana servers are in suse11-Python2, and the Taurus client is in Debian9-Python3.

I also  think so, plus one probably needs to have a measurement group already defined in the server side to be able to trigger it

This corresponds to sardana community to decide, but I personally would discard this as an unsupported configuration, rather than considering it a bug.

I am closing it here. Reopen in Sardana if you think it should be fixed.

**Closed by cpascual** 2019-10-07 07:55 UTC
Labels: bug
