### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type TaurusTrendsSet has been deleted

### ISSUE THREAD

**Issue by nfalcoz** [taurus-org/taurus#908] opened 2019-04-23 16:16 UTC
Bonjour !

En créant une plateforme d'IHM, j'ai recontré l'erreur citée en titre, au moment où je clique sur le bouton de l'ihm principale qui est censé lancer une nouvelle ihm. J'ai pu identifier la source de cette erreur, et celle-ci provient de la commande setModel() dans le code ci-dessous:

    def __init__(self, attributs, parent=None):
        # appel de l'initialisation de la classe parent 
        TaurusWidget.__init__(self, parent=parent)

        self.attributs=attributs

        ## DEBUT ZONE MODIFIABLE
        # initialisation des objets d'affichage 
        thermocoupleLabel = TaurusLabel()
        thermocoupleLecture = TaurusLabel()
        thermocoupleLectureUnite = TaurusLabel()
        panelPicPrc = TaurusTrend()
        # creation du modele : ajout de Pic (puissance incidente) et 
        # Prc (puissance réfléchie)
        modelTendancePicPrc = self.attributs["modelTendancePicPrc"]
        # panelPicPrc.setXIsTime(True)

        # association de l'objet au device
        thermocoupleLabel.setText(self.attributs["thermocoupleLabel"])
        thermocoupleLecture.setModel(self.attributs["thermocoupleLecture"])
        thermocoupleLectureUnite.setText(self.attributs["thermocoupleLectureUnite"])

        # association objet-device
        panelPicPrc.setModel(modelTendancePicPrc) #Le lancement de la nouvelle ihm fonctionne sans erreur si cette ligne est commentée

        # création et application d'un cadre visuel sous forme de grille
        layout = Qt.QGridLayout()
        self.setLayout(layout)

        # ajout des  objets de l'interface graphique
        # Pour occuper plusieurs cellules :
        # https://doc.qt.io/qt-4.8/qgridlayout.html#addWidget
        layout.addWidget(panelPicPrc, 0, 0, 1, -1)
        layout.addWidget(thermocoupleLabel, 1, 0)
        layout.addWidget(thermocoupleLecture, 1, 1)
        layout.addWidget(thermocoupleLectureUnite, 1, 2)

Ne comprenant pas pourquoi cette erreur apparait, je solicite votre aide. L'un d'entre vous aurait une idée ? Merci d'avance

**Comment by cmft** [comment] 2019-04-24 07:25
Hi @nfalcoz ,
Your widget works with dummy models (using develop). Which version of taurus are you using ?

```
if __name__ == '__main__':
    import taurus

    app = taurus.qt.qtgui.application.TaurusApplication(
        app_name="test",
        app_version=taurus.Release.version
    )

    w = SignauxHFLaser({'modelTendancePicPrc': 'sys/tg_test/1/float_scalar',
                        'thermocoupleLabel': 'sys/tg_test/1/float_scalar',
                        'thermocoupleLecture': 'sys/tg_test/1/float_scalar',
                        'thermocoupleLectureUnite': 'sys/tg_test/1/float_scalar'})
    w.show()

    sys.exit(app.exec_())
```

**Comment by nfalcoz** [comment] 2019-04-24 12:45
Hi @cmft,
I use taurus 4.4.0 and i still have the same error.

**Comment by cpascual** [comment] 2019-04-24 15:29
Hi, @nfalcoz , the snippet that you provide is not complete (e.g., it lacks the definition of the `self.attributs`). Can you provide a snippet that we can use to reproduce the issue?

Also, if possible, strip the snippet of all unrelated bits (try to give us the minimum lines necessary to reproduce the error).

Apart, here is a hint: the title mentions an error with TaurusTrendSet. It is likely that the problem comes in how you use the `panelPicPrc` (which is a TaurusTrend) , whilet all the other TaurusLabel, etc, are unrelated to this issue

**Comment by nfalcoz** [comment] 2019-04-25 14:41
Hi @cpascual ,
I'll give you another snippet where i call the variables directly : 

    def __init__(self, attributs, parent=None):
        # appel de l'initialisation de la classe parent 
        TaurusWidget.__init__(self, parent=parent)

        panelPicPrc = TaurusTrend()
        panelPicPrc.setXIsTime(True)

        panelPicPrc.setModel(['sys/tg_test/1/long64_scalar', 'sys/tg_test/1/long_scalar'])

        layout = Qt.QGridLayout()
        self.setLayout(layout)

        layout.addWidget(panelPicPrc, 0, 0, 1, -1)


Then this code is launch by the line ` panneau_signauxHF = SignauxHFLaser(self.attributs["signauxHF"])` in the main code where `self.attributs` contains values from a yml file : 

`        ModeSimulation=True
         fichierConfigSimulation="RF_Canon-simulation.yml"
         fichierConfigFonctionnement="RF_Canon.yml"

        self.attributs=[]

        if (self.ModeSimulation):
            self.fichier=self.fichierConfigSimulation
        else:
            self.fichier=self.fichierConfigFonctionnement

        with open(self.fichier, 'r') as stream:
            try:
                self.attributs=yaml.load(stream)
            except yaml.YAMLError as exc:
                print exc;`

Thanks

**Comment by cpascual** [comment] 2019-04-25 15:15
Hi @nfalcoz , unfortunately the snippet is still not something I can directly try.
For starters, there is some missing class definition (SignauxHFLaser), and also I lack info on the attribute names that you are using

For the type of problem that the title suggests, the exact detail on how you are declaring and using the objects may be critical. The type of attributes as well.

Please try to make a self-contained example which I can copy-paste and directly execute to reproduce the issue in order to be able to debug it. 
Also, if possible, try to reproduce the issue using attributes from the TangoTest DS , so that we can use the same in our tests here.

**Comment by nfalcoz** [comment] 2019-04-26 10:43
Hi @cpascual,
I've made a situation like mine in a short code that you can test directly to see my error. The first code allows to launch the second like in my application : 

`class TestTrend(TaurusWidget):

    def __init__(self, parent=None):

        # call the parent class init
        #QtGui.QWidget.__init__(self, parent=parent)
        TaurusWidget.__init__(self, parent=parent)


        layout = Qt.QGridLayout()
        self.setLayout(layout)

        btnTrend = Qt.QPushButton()
        btnTrend.setText("Trend")
        btnTrend.clicked.connect(self.LaunchTrend)


        layout.addWidget(btnTrend)


    def LaunchTrend(self):
        panelTrend = DisplayTrend()
        panelTrend.show()



if __name__ == "__main__":
    app = TaurusApplication(sys.argv)
    panel = TestTrend()
    panel.show()
    sys.exit(app.exec_())`

And the second code launch a TaurusTrend : 

`class DisplayTrend(TaurusWidget):


    def __init__(self, parent=None):

        # call the parent class init
        #QtGui.QWidget.__init__(self, parent=parent)
        TaurusWidget.__init__(self, parent=parent)

        layout = Qt.QGridLayout()
        self.setLayout(layout)

        panneau_signauxHF = SignauxHFLaser()

        layout.addWidget(panneau_signauxHF, 4, 0, 1, -1)


class SignauxHFLaser(TaurusWidget):

    def __init__(self, parent=None):
        # appel de l'initialisation de la classe parent 
        TaurusWidget.__init__(self, parent=parent)

        panelPicPrc = TaurusTrend()

        modelTendancePicPrc = ['sys/tg_test/1/long64_scalar', 'sys/tg_test/1/long_scalar']
        panelPicPrc.setXIsTime(True)

        panelPicPrc.setModel(modelTendancePicPrc)

        layout = Qt.QGridLayout()
        self.setLayout(layout)

        layout.addWidget(panelPicPrc, 0, 0, 1, -1)

if __name__ == "__main__":
    app = TaurusApplication(sys.argv)
    panel = DisplayTrend()
    panel.show()
    sys.exit(app.exec_())`

Thanks

**Comment by cpascual** [comment] 2019-04-29 13:05
ok, now I could reproduce it and debug it: your problem is caused because the `panelTrend` object created in `TestTrend.LaunchTrend` is only referenced in a local variable, so there is no permanent reference to it and the python garbage collector is removing it.


You should keep permanent references to the widgets. For example, in your case all is fixed with:

```python
class TestTrend(TaurusWidget):
    (...)
    def LaunchTrend(self):
        self.panelTrend = DisplayTrend()  # <- note the `self.` !
        self.panelTrend.show()
```



NOTE: in case you are wondering why similar code works in the case of, e.g. `btnTrend`, the reason is that i`btnTrend` is being inserted in the layout of `TestTrend`, which implicitly makes   `TestTrend` its parent, and in Qt, the parent widget internally keeps a ref to all its children (but still, IMHO it is better to follow the [Zen of Python](https://www.python.org/dev/peps/pep-0020/) when it says "explicit better than implicit")

**Closed by cpascual** 2019-04-29 13:05 UTC
