### ISSUE TITLE
(doc) document how TaurusValueLineEdit parses quantities

### ISSUE THREAD

**Issue by jairomoldes** [taurus-org/taurus#679] opened 2018-01-30 16:11 UTC
It looks like white spaces are interpreted as multiplication sign when editing the value.

To reproduce simply run the default sample code:
(e.g.) python ~/workspace/taurus/lib/taurus/qt/qtgui/input/tauruslineedit.py
and type "2 3" (withouth the quotes) and then enter. You will see that the write value of "sys/tg_test/1/double_scalar" has been change to 6 (2*3)

**Comment by cpascual** [comment] 2018-01-31 08:12
Confirmed. It comes from the parsing done by pint:

```python
In [1]: from pint import UnitRegistry

In [2]: UR = UnitRegistry()

In [3]: UR.parse_expression('2 3')
Out[3]: 6

In [4]: UR.parse_expression('2 3 m 4 s**-1')
Out[4]: <Quantity(24.0, 'meter / second')>

```

It seems to me that this is considered a feature, not a bug in pint (see https://github.com/hgrecco/pint/issues/226).
I personally prefer not to implement/maintain/document a custom parser , and so I propose to close this as "wontfix"

**Comment by jairomoldes** [comment] 2018-01-31 17:16
From my point of view this is confusing, but if you all agree that it is acceptable I will not oppose to close it as "wontfix"

**Comment by cpascual** [comment] 2018-01-31 17:27
I see your point, but I think that the confusion would be mitigated if we prominently document that the TaurusValueLineEdit will parse its contents using pint's parser (when dealing with numerical models).

So I will leave this issue open as a reminder for documenting (I'll change the title accordingly)

**Closed** 2018-07-24 06:36 UTC
Labels: enhancement
