### ISSUE TITLE
Some Macroexecutor icons are not visible (debian9)

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#578] opened 2017-09-26 06:57 UTC
In Debian9, Macroexecutor icons from 'Favorite List' and 'History Viewer' are not visible.
Even after installing using pip or python setup.py install.

Missing icons are:
- Remove all macros from history
- Remove selected macros from favorites
- Remove all macros from favorites
- Move up macro in favorite hierarchy 
- Move down macro in favorite hierarchy

**Comment by reszelaz** [comment] 2017-09-26 07:21
Thanks for the report! Just to complement it:

I'm using Debian 9 with all the Sardana dependencies installed with the official Debian packages and taurus/support-3.x and sardana/develop installed in the develop mode (python setup.py develop --user) and I don't see this problem.

**Comment by reszelaz** [comment] 2017-09-26 07:28
I can reproduce it with taurus/develop.

**Comment by cpascual** [comment] 2017-09-26 07:32
Any hints from the console output?

**Comment by cpascual** [comment] 2017-09-26 07:34
Also, are other icons visible in the same app?
If that is the case, the problem may be in how those icons are inserted. In theory taurus4 should provide backwards compatibility for the old taurus icon API, but if they were inserted in some "non-standard" way it could be failing.

**Comment by mrosanes** [comment] 2017-09-26 09:11
Yes, some icons are visible in the same app. The console output reports warnings of deprecation for the icons that are visible: thus, it is the right behavior.

As you say, maybe they are inserted in some non-stadard way, I'll have a look to it.

**Comment by mrosanes** [comment] 2017-09-28 07:09
In fact this is a bug of Sardana. Opened a pull request in Sardana for it: https://github.com/sardana-org/sardana/pull/616

**Comment by cpascual** [comment] 2017-09-28 07:49
Closing as rejected since this is a bug in Sardana

**Closed by cpascual** 2017-09-28 07:49 UTC
Labels: rejected
