### ISSUE TITLE
TaurusCommandButton problem with useParentModel and tango device server not started when setting model

### ISSUE THREAD

**Issue by CorF4** [taurus-org/taurus#732] opened 2018-04-10 10:46 UTC
Hi,
I am testing my gui's in some scenarios where the tango device server is unavailable, i.e. not running. Let's say I have a running device server and launch the gui after starting the device server. If I stop the device server, the fields on the gui are disconnected, naturally. If I start the server again, after a few seconds the fields are able to re-connect and show the corresponding content. If I launch a gui containing taurusLabel and taurusCommandButton before I start the corresponding device server, the fields are disconnected, if the device servers is running, they are able to reconnect. So far so good. However, if I use useParentModel = True for these objects and start the gui before the device server, the taurusCommandButton seems to have no model attached, even if the device server is available again.

I post here an example to be tested with the TangoTest device server:

```
from taurus.external.qt import Qt, QtCore
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.container import TaurusFrame
from taurus.qt.qtgui.display import TaurusLabel
from taurus.qt.qtgui.button import TaurusCommandButton

if __name__ == '__main__':

    app = TaurusApplication(app_name='MyGui')
    panel = Qt.QWidget()
    
    frame = TaurusFrame(panel)
    frame.resize(200,200)
    frame.model = "sys/tg_test/1"
    
    label = TaurusLabel(frame)
    label.useParentModel = True
    label.model = "/double_scalar"
    label.resize(100,20)
    label.move(50,0)
    
    labelState = TaurusLabel(frame)
    labelState.move(50,50)
    labelState.useParentModel = True
    labelState.model = "/State"
    labelState.resize(100,20)
    
    button = TaurusCommandButton(frame)
    button.move(50,100)
    button.setUseParentModel(True)
    button.setCommand("SwitchStates")
    
    panel.show()
    app.exec_()
```

If I start the device server after launching this script and try to press the taurusCommandButton, I get the following message:

`MainThread     WARNING  2018-04-10 12:26:00,916 TaurusCommandButton: Device None does not implement command SwitchStates`

The taurusLabels however can display the correct content. I haven't tested other widgets yet.

Do you have an idea what is happening? Let me know if you need more info, or I wasn't clear enough.
Thanks!

**Comment by CorF4** [comment] 2018-04-11 08:28
There is another point if you mix in taurusdesigner:

- **First case:** create a ui file that has a frame, a label and a command button. Don't specify models. In the ui file, add outside the frame a command button with specified model.
Launch the script before the device server: observation: taurusLabels inside the taurusFrame aren't even visible. 
This does not occur if there is no command button outside the frame.

- **Second case:** Create a ui file as above without an object outside of the frame. In the launcher script add another frame to the panel with a label and a command button.
Launch the script before the device server: observation: taurusLabels in the frame added in python code aren't visible.

For both cases the TaurusCommandButton is not working in any frame.

We know these are special use case constructs, but we want to give you as much informations as we can. We use taurus version **4.3.1**.
It is unclear what the ui-file usage is provoking, but it seems that also the TaurusLabel may have some problems in some use case scenarios.

Example codes, first case:
ui-file: tangotest.ui
```
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>Form</class>
 <widget class="QWidget" name="Form">
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>400</width>
    <height>300</height>
   </rect>
  </property>
  <property name="windowTitle">
   <string>Form</string>
  </property>
  <widget class="TaurusFrame" name="taurusFrame">
   <property name="geometry">
    <rect>
     <x>30</x>
     <y>20</y>
     <width>311</width>
     <height>111</height>
    </rect>
   </property>
   <widget class="TaurusCommandButton" name="taurusCommandButton">
    <property name="geometry">
     <rect>
      <x>50</x>
      <y>10</y>
      <width>221</width>
      <height>27</height>
     </rect>
    </property>
    <property name="UseParentModel">
     <bool>true</bool>
    </property>
    <property name="Command">
     <string>SwitchStates</string>
    </property>
   </widget>
   <widget class="TaurusLabel" name="taurusLabel">
    <property name="geometry">
     <rect>
      <x>50</x>
      <y>60</y>
      <width>231</width>
      <height>21</height>
     </rect>
    </property>
    <property name="model">
     <string>/double_scalar</string>
    </property>
    <property name="useParentModel">
     <bool>true</bool>
    </property>
   </widget>
  </widget>
  <widget class="TaurusCommandButton" name="taurusCommandButton_2">
   <property name="geometry">
    <rect>
     <x>130</x>
     <y>170</y>
     <width>211</width>
     <height>27</height>
    </rect>
   </property>
   <property name="Model">
    <string>/sys/tg_test/1</string>
   </property>
   <property name="Command">
    <string>SwitchStates</string>
   </property>
  </widget>
 </widget>
 <customwidgets>
  <customwidget>
   <class>TaurusFrame</class>
   <extends>QFrame</extends>
   <header>taurus.qt.qtgui.container</header>
   <container>1</container>
  </customwidget>
  <customwidget>
   <class>TaurusLabel</class>
   <extends>QLabel</extends>
   <header>taurus.qt.qtgui.display</header>
  </customwidget>
  <customwidget>
   <class>TaurusCommandButton</class>
   <extends>QPushButton</extends>
   <header>taurus.qt.qtgui.button</header>
  </customwidget>
 </customwidgets>
 <resources/>
 <connections/>
</ui>
```
launch with this script:
```
from taurus.external.qt import Qt,QtCore
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.util.ui import UILoadable

@UILoadable
class tangotest(Qt.QWidget):

    def __init__(self, parent=None):
        Qt.QWidget.__init__(self, parent)

        self.loadUi()

        self.taurusFrame.setModel("sys/tg_test/1")
        
if __name__ == '__main__':
    app = TaurusApplication(app_name='Simple')

    panel = tangotest()
    panel.show()
    app.exec_()
```

Example codes, second case:
taurusdesigner.ui:
```
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>Form</class>
 <widget class="QWidget" name="Form">
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>513</width>
    <height>486</height>
   </rect>
  </property>
  <property name="windowTitle">
   <string>Form</string>
  </property>
  <widget class="TaurusFrame" name="taurusFrame">
   <property name="geometry">
    <rect>
     <x>0</x>
     <y>20</y>
     <width>451</width>
     <height>151</height>
    </rect>
   </property>
   <widget class="TaurusLabel" name="taurusLabel">
    <property name="geometry">
     <rect>
      <x>20</x>
      <y>10</y>
      <width>271</width>
      <height>31</height>
     </rect>
    </property>
    <property name="model">
     <string>/double_scalar</string>
    </property>
    <property name="useParentModel">
     <bool>true</bool>
    </property>
   </widget>
   <widget class="TaurusCommandButton" name="taurusCommandButton">
    <property name="geometry">
     <rect>
      <x>20</x>
      <y>60</y>
      <width>271</width>
      <height>41</height>
     </rect>
    </property>
    <property name="Model">
     <string/>
    </property>
    <property name="UseParentModel">
     <bool>true</bool>
    </property>
    <property name="Command">
     <string>SwitchStates</string>
    </property>
   </widget>
   <widget class="TaurusLabel" name="taurusLabel_2">
    <property name="geometry">
     <rect>
      <x>20</x>
      <y>110</y>
      <width>271</width>
      <height>31</height>
     </rect>
    </property>
    <property name="model">
     <string>/State</string>
    </property>
    <property name="useParentModel">
     <bool>true</bool>
    </property>
   </widget>
  </widget>
 </widget>
 <customwidgets>
  <customwidget>
   <class>TaurusFrame</class>
   <extends>QFrame</extends>
   <header>taurus.qt.qtgui.container</header>
   <container>1</container>
  </customwidget>
  <customwidget>
   <class>TaurusLabel</class>
   <extends>QLabel</extends>
   <header>taurus.qt.qtgui.display</header>
  </customwidget>
  <customwidget>
   <class>TaurusCommandButton</class>
   <extends>QPushButton</extends>
   <header>taurus.qt.qtgui.button</header>
  </customwidget>
 </customwidgets>
 <resources/>
 <connections/>
</ui>
```
launcher script:
```
from taurus.external.qt import Qt, QtCore
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.container import TaurusFrame
from taurus.qt.qtgui.display import TaurusLabel
from taurus.qt.qtgui.button import TaurusCommandButton
from taurus.qt.qtgui.util.ui import UILoadable

@UILoadable
class taurusdesigner(Qt.QWidget):

    def __init__(self, model=None, parent=None):
        Qt.QWidget.__init__(self, parent)

        self.loadUi()

        self.taurusFrame.setModel(model)
        

if __name__ == '__main__':

    app = TaurusApplication(app_name='MyGui')
    #panel = Qt.QWidget()
    panel = taurusdesigner("sys/tg_test/1")
    
    frame = TaurusFrame(panel)
    frame.resize(200,300)
    frame.move(100,200)
    frame.model = "sys/tg_test/1"
    
    label = TaurusLabel(frame)
    label.useParentModel = True
    label.model = "/double_scalar"
    label.resize(100,20)
    label.move(50,100)
    
    labelState = TaurusLabel(frame)
    labelState.move(50,150)
    labelState.useParentModel = True
    labelState.model = "/State"
    labelState.resize(100,20)
    
    button = TaurusCommandButton(frame)
    button.move(50,200)
    button.setUseParentModel(True)
    button.setCommand("SwitchStates")
    
    panel.show()
    app.exec_()
```

**Comment by cpascual** [comment] 2018-04-11 15:44
Regarding the problem reported in your [inital comment](https://github.com/taurus-org/taurus/issues/732#issue-312869043), I confirm it. It is clearly a bug. 
It looks like the reconnection is not done properly in the case of using the parent model

**Comment by cpascual** [comment] 2018-04-11 17:06
Regarding the case1 and 2 of the [second comment](https://github.com/taurus-org/taurus/issues/732#issuecomment-380371131), I can also confirm that I reproduce them.
Note that in both cases the widgets respond properly to in the following scenario:
A1- launch the device
A2- launch the gui
A3-stop the device
A4- start the device

While they do not work properly when doing 
B1- stop the device
B2- launch the GUI
B3- restart the device

This indicates that the problem is that some required initialization that occurs in A2 and which is not done in B2 (due to the lack of connection) should be done as soon as an event arrives after B3.

PS: In any case, this is related to the useParentModel feature, which [I *personally* recommend to avoid ](https://github.com/taurus-org/taurus/issues/676#issuecomment-361184947). Now I am going a step further and publicly opening the debate on whether the useParentModel feature should be kept or not. So, anyone with an opinion about it, please join the discussion in #734

**Comment by cpascual** [comment] 2019-07-01 08:24
Hi since we officially deprecated the useParentModel feature, I am closing this as "won't fix"

**Closed by cpascual** 2019-07-01 08:24 UTC
Labels: bug
